version: '2.1'
orbs:
  sysdig: sysdig/sysdig@2.0.0
jobs:
  build-and-scan:
    docker:
      - image: 'cimg/base:stable'
    environment:
      IMAGE_TO_BUILD: 'nginx:latest'
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: 'docker build -t ${IMAGE_TO_BUILD} .'
          name: Build Docker image
      - sysdig/inline-image-scan:
          image-tag: '${IMAGE_TO_BUILD}'
          input-type: docker-daemon
          sysdig-secure-token: SECURE_API_TOKEN
workflows: null
