jobs:
<<<<<<< HEAD
  build:
#    machine:
#       image: ubuntu-2204:2022.04.2

    docker:
      - image: cimg/base:2022.09
      
    environment:
      TAG:
      
    working_directory: /mnt/ramdisk

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: "Setup custom environment variables"
          command: echo 'export TAG="0.1.${CIRCLE_BUILD_NUM}"' >> "$BASH_ENV"

      - run:
          name: "Build docker image"
          command: |
            docker build -t node-hello-world:${TAG} .
      - run: 
          name: "Download Sysdig CLI scanner" 
          command: |
            echo 'Downloading most recent Sysdig CLI scanner'
            curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
            chmod +x ./sysdig-cli-scanner
          
      - run:
          name: "Scan image with Sysdig CLI scanner"
          command: ./sysdig-cli-scanner --console-log --apiurl $SYSDIG_SECURE_API docker://node-hello-world:${TAG}
=======
  scan-image-from-registry:
    docker:
      - image: 'cimg/base:stable'
    environment:
      IMAGE_TO_PULL_AND_SCAN: 'nginx:latest'
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - sysdig/inline-image-scan:
          image-tag: '${IMAGE_TO_PULL_AND_SCAN}'
          input-type: pull
          sysdig-secure-token: SECURE_API_TOKEN
workflows:
  scan:
    jobs:
      - scan-image-from-registry 
>>>>>>> refs/remotes/origin/main
