version: '2.1'
orbs:
  sysdig: sysdig/sysdig@2.0.0
jobs:
  scan-image-from-registry:
    docker:
      - image: 'cimg/base:stable'
    environment:
      IMAGE_TO_PULL_AND_SCAN: 'nginx:latest'
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - sysdig/inline-image-scan:
          image-tag: '${IMAGE_TO_PULL_AND_SCAN}'
          input-type: pull
          sysdig-secure-token: SECURE_API_TOKEN
workflows: null
